# Qserv operator CI workflow
---
name: "CI"
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  main:
    name: Validate k8s install
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create k8s/kind cluster
        run: |
          git clone --depth 1 -b "k8s-v1.20.2-1" --single-branch https://github.com/k8s-school/kind-helper.git
          ./kind-helper/k8s-create.sh -s
      - name: Install argo workflow
        run: |
          ./workflow/install.sh
      - name: Install argo client
        run: |
          ./argo-client-install.sh
      - name: Run test on authorization
        run: |
          ./workflow/test.sh
